import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Image from "next/image";
import bg from '../../public/wave2bg.png'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Faceio Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-full w-full flex flex-col items-center justify-center relative">
        <Image src={bg} alt="background" fill={true} className='-z-10' unoptimized={true}/>

          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
